version: '3'

services:
  database:
    container_name: application_db
    build:
      context: .
      dockerfile: Dockerfile.database
    image: comp_dist_database:initial
    environment:
      MYSQL_USER_ROOT : root
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE: trabalho_comp_2
    restart: unless-stopped

  web_server_java:
    container_name: web_server_java
    build:
      context: .
      dockerfile: Dockerfile.application
    image: comp_dist_java_application:initial
    ports:
      - 8080:8080
    depends_on:
      - database
    restart: unless-stopped

  